"""conformance/cases/vision_orchestration.json asserted as a BINDING contract (§9).

The two-phase vision seam (ADR-0005) is emit -> fulfil -> assemble, and only the
raw model call in the middle is per-host. Everything around it is deterministic
orchestration, so the fixture pins it for every port:
``golang/vision/vision_conformance_test.go`` and
``js/src/vision/vision-conformance.test.ts`` hold Go and JS to exactly this file.
This is the Python side, which the fixture had none of — it was generated by
``python/scripts/gen_conformance.py:1206`` and asserted by nobody.

Discipline, per the repo's conformance rule: every expectation is READ FROM the
committed JSON, never re-derived by calling the code under test, and every count
is pinned EXACTLY rather than floored at ``> 0``. The one thing deliberately NOT
read from the fixture is the prompt fed into the emit phase — that comes from the
shipped constant, so this test fails if the shipped prompt drifts from the pinned
one instead of quietly agreeing with itself.
"""

from __future__ import annotations

import base64
from typing import Any

import pytest

from citenexus.domain.partition import PartitionPath
from citenexus.domain.vision import PendingVisionRequest
from citenexus.vision.client import _VISION_PROMPT
from citenexus.vision.describe import record_from_mapping
from citenexus.vision.fulfill import fulfill_vision_requests
from citenexus.vision.requests import build_pending_request
from citenexus.vision.units import build_vision_units

from .fixtures import load_case, load_data

CASE: dict[str, Any] = load_case("vision_orchestration.json")
PROMPTS: dict[str, str] = load_data("prompts.json")

# Pinned EXACTLY. A vector silently dropped is a weakened contract no per-case
# assertion can see.
EXPECTED_IMAGES = 2
EXPECTED_EMITTED = 2
EXPECTED_FULFILLED = 2
EXPECTED_ASSEMBLED = 2
EXPECTED_DEGRADED_UNITS = 1

# The partition the fixture's assembled EUs carry, read from the fixture itself.
PARTITION = PartitionPath.model_validate(CASE["assembled_eus"][0]["partition"])


class _FixtureVision:
    """A stand-in for the injected vision model that replays the fixture.

    It speaks the two-phase contract (``describe_payload``), so the reference
    fulfiller hands it the emitted payload VERBATIM — the same shape a Go or JS
    host implements. Keying the replay on the emitted ``image_url`` is what makes
    the substitution honest: a port that emitted a different data URI would not
    find its response here.
    """

    def __init__(self, responses: dict[str, dict[str, Any]], failing: frozenset[str] = frozenset()):
        self._responses = responses
        self._failing = failing

    def describe_payload(self, image_url: str, prompt: str) -> dict[str, Any]:
        if image_url in self._failing:
            raise RuntimeError("vision endpoint failed for this image")
        assert prompt == _VISION_PROMPT, "the host must be handed the emitted prompt verbatim"
        return self._responses[image_url]


def _emit() -> list[PendingVisionRequest]:
    """Drive the fixture's images through the real emit phase."""
    return [
        build_pending_request(
            document_id=CASE["document_id"],
            image_id=image["image_id"],
            data=base64.b64decode(image["bytes_b64"]),
            prompt=_VISION_PROMPT,
            page=expected["source_ref"]["page"],
            bbox=tuple(expected["source_ref"]["bbox"]),
            source_uri=CASE["source_uri"],
        )
        for image, expected in zip(CASE["images"], CASE["emit"], strict=True)
    ]


def _responses_by_image_url() -> dict[str, dict[str, Any]]:
    """The fixture's own fulfilled mappings, addressed by emitted image_url."""
    return {
        emitted["payload"]["image_url"]: CASE["fulfilled"][emitted["request_id"]]
        for emitted in CASE["emit"]
    }


def test_vector_counts_are_pinned() -> None:
    assert len(CASE["images"]) == EXPECTED_IMAGES
    assert len(CASE["emit"]) == EXPECTED_EMITTED
    assert len(CASE["fulfilled"]) == EXPECTED_FULFILLED
    assert len(CASE["assembled_eus"]) == EXPECTED_ASSEMBLED
    assert len(CASE["degrade"]["assembled_eu_ids"]) == EXPECTED_DEGRADED_UNITS


def test_the_shipped_prompt_is_the_pinned_prompt() -> None:
    """The prompt rides in every payload the host POSTs verbatim, so a paraphrase
    is a different model input — pinned as tier-2 shared data (ADR-0010)."""
    assert PROMPTS["vision_describe"] == _VISION_PROMPT
    for emitted in CASE["emit"]:
        assert emitted["payload"]["prompt"] == PROMPTS["vision_describe"]


def test_the_two_images_pin_distinct_sniffed_media_types() -> None:
    """The fixture's value is that the payload declares each image's TRUE type;
    two identical media types would pin nothing."""
    subtypes = [e["payload"]["image_url"].split(";", 1)[0] for e in CASE["emit"]]
    assert subtypes == ["data:image/png", "data:image/jpeg"]


@pytest.mark.parametrize(
    "index", [pytest.param(i, id=CASE["emit"][i]["request_id"]) for i in range(EXPECTED_EMITTED)]
)
def test_emitted_request_matches_the_fixture(index: int) -> None:
    assert _emit()[index].model_dump(mode="json") == CASE["emit"][index]


def test_no_emitted_payload_carries_a_credential() -> None:
    """The load-bearing ADR-0005 invariant: the emit phase produces image content
    and a prompt, and nothing a key could hide in."""
    for request in _emit():
        assert set(request.payload.model_dump()) == {"prompt", "image_url"}


@pytest.mark.parametrize("request_id", [pytest.param(rid, id=rid) for rid in CASE["fulfilled"]])
def test_record_from_mapping_matches_the_fixture(request_id: str) -> None:
    expected = CASE["fulfilled"][request_id]
    record = record_from_mapping(expected["image_id"], expected)
    assert record.model_dump(mode="json") == expected


def test_fulfil_joins_every_response_by_request_id() -> None:
    fulfilled = fulfill_vision_requests(_emit(), _FixtureVision(_responses_by_image_url()))
    assert {rid: rec.model_dump(mode="json") for rid, rec in fulfilled.items()} == CASE["fulfilled"]


def test_assembled_units_match_the_fixture() -> None:
    requests = _emit()
    fulfilled = fulfill_vision_requests(requests, _FixtureVision(_responses_by_image_url()))
    units = build_vision_units(requests, fulfilled, partition=PARTITION, language=CASE["language"])
    assert [u.model_dump(mode="json") for u in units] == CASE["assembled_eus"]


def test_a_failing_model_call_degrades_and_never_fabricates() -> None:
    """The degrade path, driven end-to-end: the first image's model call FAILS.

    Per-request isolation means the second image still produces its unit, and the
    first produces none — not an empty caption, not a placeholder. The fixture
    pins both halves.
    """
    requests = _emit()
    failing = frozenset({requests[0].payload.image_url})
    fulfilled = fulfill_vision_requests(
        requests, _FixtureVision(_responses_by_image_url(), failing=failing)
    )
    assert {rid: rec.model_dump(mode="json") for rid, rec in fulfilled.items()} == (
        CASE["degrade"]["fulfilled"]
    )

    units = build_vision_units(requests, fulfilled, partition=PARTITION, language=CASE["language"])
    assert [u.eu_id for u in units] == CASE["degrade"]["assembled_eu_ids"]
    # Nothing was invented for the failed image.
    assert requests[0].request_id not in {u.eu_id for u in units}


def test_an_empty_description_yields_no_unit() -> None:
    """A model that returns junk (no caption, no description) must also degrade —
    an EU whose text is empty is a citation to nothing."""
    requests = _emit()
    fulfilled = fulfill_vision_requests(
        requests, _FixtureVision({url: {} for url in _responses_by_image_url()})
    )
    assert len(fulfilled) == EXPECTED_FULFILLED
    units = build_vision_units(requests, fulfilled, partition=PARTITION, language=CASE["language"])
    assert units == []
