// GENERATED by python/scripts/gen_conflict_tables.py — DO NOT EDIT.
//
// Source of truth: <repo>/conformance/conflict.json (ADR-0007, ADR-0010 tier 2).
// Regenerate with: cd python && uv run python scripts/gen_conflict_tables.py
//
// The JSON is EMBEDDED (a copy of conformance/conflict.json) so this module is
// self-contained as a Go dependency: a filesystem read of the shared
// conformance/ dir does not exist in the module cache. Same mechanism as
// golang/gate/stopwords.json and golang/answer/segmentation.json.

package answer

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed conflict_tables.json
var conflictTablesJSON []byte

// ConflictThresholds are the pinned ADR-0007 constants. They are data, on
// purpose: a port that quietly relaxes MaxResidual to 2 buys 4pp of recall and
// pays 15pp of false abstention, and pinning the number in the shared contract
// is the only way to catch that across languages.
type ConflictThresholds struct {
	SubjectOverlap          float64 `json:"subject_overlap"`
	MaxSymdiff              int     `json:"max_symdiff"`
	MaxResidual             int     `json:"max_residual"`
	MinContent              int     `json:"min_content"`
	DuplicateJaccard        float64 `json:"duplicate_jaccard"`
	DuplicateMaxLengthDelta int     `json:"duplicate_max_length_delta"`
	TopK                    int     `json:"top_k"`
}

// ConflictTables is the canonical ADR-0007 table set.
type ConflictTables struct {
	Languages        []string           `json:"languages"`
	Negations        []string           `json:"negations"`
	Antonyms         [][]string         `json:"antonyms"`
	ReportBigrams    [][]string         `json:"report_bigrams"`
	ScopeMarkers     []string           `json:"scope_markers"`
	MeasurementUnits []string           `json:"measurement_units"`
	Thresholds       ConflictThresholds `json:"thresholds"`
}

var (
	conflictTablesOnce sync.Once
	conflictTables     ConflictTables
)

// LoadConflictTables parses and caches the embedded canonical tables.
func LoadConflictTables() ConflictTables {
	conflictTablesOnce.Do(func() {
		if err := json.Unmarshal(conflictTablesJSON, &conflictTables); err != nil {
			panic("answer: unmarshal conflict_tables.json: " + err.Error())
		}
	})
	return conflictTables
}

// ConflictNegationSet returns the negation markers as a set.
func ConflictNegationSet() map[string]struct{} {
	return stringSet(LoadConflictTables().Negations)
}

// ConflictScopeMarkerSet returns the scope qualifiers as a set.
func ConflictScopeMarkerSet() map[string]struct{} {
	return stringSet(LoadConflictTables().ScopeMarkers)
}

// MeasurementUnitSet returns the unit tokens as a set.
func MeasurementUnitSet() map[string]struct{} {
	return stringSet(LoadConflictTables().MeasurementUnits)
}

// ConflictAntonymSet returns the antonym pairs SYMMETRISED — the canonical file
// stores each pair in one direction only.
func ConflictAntonymSet() map[[2]string]struct{} {
	out := map[[2]string]struct{}{}
	for _, pair := range LoadConflictTables().Antonyms {
		out[[2]string{pair[0], pair[1]}] = struct{}{}
		out[[2]string{pair[1], pair[0]}] = struct{}{}
	}
	return out
}

// ConflictReportBigramSet returns the reported-speech bigrams as a set. These
// are BIGRAMS deliberately: as unigrams they disable conflict detection across
// most legal text, where "claim" is a noun of art.
func ConflictReportBigramSet() map[[2]string]struct{} {
	out := map[[2]string]struct{}{}
	for _, pair := range LoadConflictTables().ReportBigrams {
		out[[2]string{pair[0], pair[1]}] = struct{}{}
	}
	return out
}

func stringSet(values []string) map[string]struct{} {
	out := make(map[string]struct{}, len(values))
	for _, v := range values {
		out[v] = struct{}{}
	}
	return out
}
