// Generates src/gen/tables.ts from the canonical conformance tables.
//
// Runtime modules (gate, verify-v2, segment) must NOT read conformance/ from the
// filesystem: that directory is not published (package.json `files` is ["dist"]),
// and from node_modules/@muthuishere/citenexus/dist/conform/ the relative path
// resolves to node_modules/conformance, which does not exist. Importing the gate
// therefore threw for every npm consumer.
//
// ADR-0010 tier 2: one canonical definition, every copy GENERATED. This is the
// JS port's generation step — the mirror of Go's //go:embed of the same files.
// A drift-guard test compares the emitted module back to conformance/.
//
// Run: node scripts/gen-tables.mjs   (wired as `prebuild` and `pretest`)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const conformanceDir = join(here, "..", "..", "conformance");
const outDir = join(here, "..", "src", "gen");

const read = (name) => JSON.parse(readFileSync(join(conformanceDir, name), "utf8"));

const stopwords = read("stopwords.json");
const polarity = read("polarity.json");
const segmentation = read("segmentation.json");
// ADR-0011: the script CLAIM lives in the per-script golden fixture, so the
// claim and its evidence are the same artifact.
const tokenizeV2 = read("cases/tokenize_v2.json");
// The named code sets (change: language-enums): one canonical table, three
// ports pinned to it. Bundled for the same reason as the script claim above.
const languages = read("cases/languages.json");

const lit = (value) => JSON.stringify(value, null, 2);

const out = `// GENERATED by scripts/gen-tables.mjs — DO NOT EDIT.
// Source of truth: <repo>/conformance/{stopwords,polarity,segmentation}.json
//                  <repo>/conformance/cases/tokenize_v2.json (script claim)
//                  <repo>/conformance/cases/languages.json (named code sets)
// Regenerate with: node scripts/gen-tables.mjs
//
// Bundled rather than read from disk so the published package is self-contained.

export const STOPWORDS_TABLE: readonly string[] = ${lit(stopwords)};

export const POLARITY_TABLE: {
  readonly languages: readonly string[];
  readonly markers: readonly string[];
} = ${lit(polarity)};

export const SEGMENTATION_TABLE: {
  readonly terminators: readonly string[];
  readonly abbreviations: readonly string[];
} = ${lit(segmentation)};

export const SUPPORTED_SCRIPTS_TABLE: readonly string[] = ${lit(tokenizeV2.supported_scripts)};

export const CONTINUOUS_SCRIPTS_TABLE: readonly string[] = ${lit(tokenizeV2.continuous_scripts)};

export const TOKENIZER_VERSION_TABLE: number = ${lit(tokenizeV2.tokenizer_version)};

export const LANGUAGES_TABLE: readonly {
  readonly code: string;
  readonly name: string;
  readonly scripts: readonly string[];
  readonly supported: boolean;
}[] = ${lit(languages.languages)};

export const SCRIPTS_TABLE: readonly string[] = ${lit(languages.scripts)};

export const AUTO_SENTINEL_TABLE: string = ${lit(languages.auto_sentinel)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "tables.ts"), out, "utf8");
console.log("wrote src/gen/tables.ts");
