"""Typed configuration, the signal-capability gate, and warn-only validation (§15, §17)."""

from citenexus.config.loader import from_config
from citenexus.config.schema import (
    AccessControlConfig,
    CiteNexusConfig,
    EmbeddingConfig,
    GraphConfig,
    JudgeConfig,
    LexicalSignal,
    LLMConfig,
    MemoryConfig,
    MultilingualConfig,
    ProvenanceConfig,
    RerankerConfig,
    RetrievalConfig,
    StorageConfig,
    StreamingConfig,
    TelemetryConfig,
    TrustConfig,
    VectorStoreConfig,
    VisionConfig,
    VisionPrefilterConfig,
    WorkerConfig,
)
from citenexus.config.signals import (
    SLOW_PATH_SIGNALS,
    Signal,
    all_signals,
    ask_queries,
    ingest_builds,
    requires_slow_path,
    resolve_signals,
)
from citenexus.config.validate import validate_client

__all__ = [
    "SLOW_PATH_SIGNALS",
    "AccessControlConfig",
    "CiteNexusConfig",
    "EmbeddingConfig",
    "GraphConfig",
    "JudgeConfig",
    "LLMConfig",
    "LexicalSignal",
    "MemoryConfig",
    "MultilingualConfig",
    "ProvenanceConfig",
    "RerankerConfig",
    "RetrievalConfig",
    "Signal",
    "StorageConfig",
    "StreamingConfig",
    "TelemetryConfig",
    "TrustConfig",
    "VectorStoreConfig",
    "VisionConfig",
    "VisionPrefilterConfig",
    "WorkerConfig",
    "all_signals",
    "ask_queries",
    "from_config",
    "ingest_builds",
    "requires_slow_path",
    "resolve_signals",
    "validate_client",
]
