"""Generate the per-port pinned vision prompt from ONE canonical file.

ADR-0010 tier 2: a pinned prompt is language-dependent *data*, so there is
exactly one canonical definition and every port's copy is GENERATED, never
hand-copied into three files. The canonical definition is
``conformance/prompts.json`` — the file the conformance contract already
publishes (§10) — whose ``vision_describe`` key is the byte-for-byte prompt the
two-phase vision emit phase puts in every ``PendingVisionRequest`` payload.

Why every port carries a *copy* instead of reading ``conformance/`` at runtime:
that directory is not published by any of the three packages (the Go module
cache has no repo root, the npm package ships only ``dist/``). Identical
reasoning to ``gen_conflict_tables.py``; this follows it rather than inventing a
second mechanism.

Emits:

* ``golang/vision/prompts.json`` + ``prompts.go`` — //go:embed, mirroring
  ``golang/answer/conflict_tables.json``
* ``js/src/gen/prompts.ts`` — literals, mirroring ``js/src/gen/conflict_tables.ts``

Python is not emitted to: the prompt's origin is
``citenexus.vision.client._VISION_PROMPT``, which ``gen_conformance.py:83``
already writes *into* the canonical file. A test in each port asserts the loaded
prompt equals ``conformance/prompts.json``, so drift is caught at the value
level rather than by byte-comparing generated source.

Run:

    cd python && uv run python scripts/gen_vision_prompt.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[2]
CANONICAL = _REPO_ROOT / "conformance" / "prompts.json"

GO_JSON_OUT = _REPO_ROOT / "golang" / "vision" / "prompts.json"
GO_OUT = _REPO_ROOT / "golang" / "vision" / "prompts.go"
TS_OUT = _REPO_ROOT / "js" / "src" / "gen" / "prompts.ts"

_BANNER = "GENERATED by python/scripts/gen_vision_prompt.py — DO NOT EDIT."
_SOURCE = "Source of truth: <repo>/conformance/prompts.json (ADR-0005, ADR-0010 tier 2)."
_REGEN = "Regenerate with: cd python && uv run python scripts/gen_vision_prompt.py"


def load() -> dict[str, Any]:
    return json.loads(CANONICAL.read_text(encoding="utf-8"))


_GO = """// {banner}
//
// {source}
// {regen}
//
// The JSON is EMBEDDED (a copy of conformance/prompts.json) so this package is
// self-contained as a Go dependency: a filesystem read of the shared
// conformance/ dir does not exist in the module cache. Same mechanism as
// golang/answer/conflict_tables.json and golang/gate/stopwords.json.

package vision

import (
\t_ "embed"
\t"encoding/json"
\t"sync"
)

//go:embed prompts.json
var promptsJSON []byte

var (
\tpromptsOnce sync.Once
\tprompts     map[string]string
)

// Prompts parses and caches the embedded canonical prompt table.
func Prompts() map[string]string {{
\tpromptsOnce.Do(func() {{
\t\tif err := json.Unmarshal(promptsJSON, &prompts); err != nil {{
\t\t\tpanic("vision: unmarshal prompts.json: " + err.Error())
\t\t}}
\t}})
\treturn prompts
}}

// DescribePrompt is the pinned "vision_describe" prompt every emitted
// PendingRequest payload carries. It must be byte-identical across ports: the
// host POSTs the emitted payload VERBATIM, so a paraphrase here is a different
// model input and a different description in one language only.
func DescribePrompt() string {{
\treturn Prompts()["vision_describe"]
}}
"""


def render_go() -> str:
    return _GO.format(banner=_BANNER, source=_SOURCE, regen=_REGEN)


def render_ts(table: dict[str, Any]) -> str:
    return f"""// {_BANNER}
// {_SOURCE}
// {_REGEN}
//
// Bundled rather than read from disk so the published package is self-contained
// (package.json `files` is ["dist"]; conformance/ is not published).

/** The pinned `vision_describe` prompt every emitted vision payload carries.
 *  Byte-identical across ports by construction — the host POSTs the emitted
 *  payload VERBATIM, so a paraphrase is a different model input in one language
 *  only. */
export const VISION_DESCRIBE_PROMPT = {json.dumps(table["vision_describe"], ensure_ascii=False)};
"""


def generate() -> dict[Path, str]:
    """All emitted artifacts as {absolute path: text}."""
    table = load()
    return {
        GO_JSON_OUT: CANONICAL.read_text(encoding="utf-8"),
        GO_OUT: render_go(),
        TS_OUT: render_ts(table),
    }


def main() -> None:
    for path, text in generate().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(_REPO_ROOT)}")


if __name__ == "__main__":
    main()
