"""Generate the per-port ADR-0007 conflict tables from ONE canonical file.

ADR-0010 tier 2: a language-dependent *table* is the asset and the code reading
it is trivial, so there is exactly one canonical definition and every port's
copy is GENERATED, never hand-maintained. The canonical definition is
``conformance/conflict.json`` — the file the conformance contract already
publishes (§10) — and this script is the generation step for all three ports.

Why every port carries a *copy* instead of reading ``conformance/`` at runtime:
that directory is not published by any of the three packages. The Go module
cache has no repo root, the npm package ships only ``dist/``, and the Python
wheel ships only ``src/citenexus``. This is the same reasoning already written
into ``js/scripts/gen-tables.mjs`` and ``golang/gate/gate.go``; conflict tables
follow it rather than inventing a second mechanism.

Emits:

* ``python/src/citenexus/answer/gen/conflict_tables.py`` — frozenset literals
* ``golang/answer/conflict_tables.json`` + ``conflict_tables.go`` — //go:embed,
  mirroring ``golang/gate/stopwords.json`` and ``golang/answer/segmentation.json``
* ``js/src/gen/conflict_tables.ts`` — literals, mirroring ``js/src/gen/tables.ts``

Run:

    uv run python scripts/gen_conflict_tables.py

Drift is guarded at the *value* level in each port's test suite (the loaded
tables must equal ``conformance/conflict.json``), not by byte-comparing
generated source, so a formatter may reformat the output freely.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[2]
CANONICAL = _REPO_ROOT / "conformance" / "conflict.json"

PY_OUT = _REPO_ROOT / "python" / "src" / "citenexus" / "answer" / "gen" / "conflict_tables.py"
GO_JSON_OUT = _REPO_ROOT / "golang" / "answer" / "conflict_tables.json"
GO_OUT = _REPO_ROOT / "golang" / "answer" / "conflict_tables.go"
TS_OUT = _REPO_ROOT / "js" / "src" / "gen" / "conflict_tables.ts"

_BANNER = "GENERATED by python/scripts/gen_conflict_tables.py — DO NOT EDIT."
_SOURCE = "Source of truth: <repo>/conformance/conflict.json (ADR-0007, ADR-0010 tier 2)."
_REGEN = "Regenerate with: cd python && uv run python scripts/gen_conflict_tables.py"


def load() -> dict[str, Any]:
    return json.loads(CANONICAL.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- #
# Python
# --------------------------------------------------------------------------- #


def _py_strs(name: str, values: list[str]) -> str:
    body = "".join(f"        {json.dumps(v)},\n" for v in values)
    return f"{name}: frozenset[str] = frozenset(\n    {{\n{body}    }}\n)\n"


def _py_pairs(name: str, values: list[list[str]]) -> str:
    body = "".join(f"        ({json.dumps(a)}, {json.dumps(b)}),\n" for a, b in values)
    return f"{name}: frozenset[tuple[str, str]] = frozenset(\n    {{\n{body}    }}\n)\n"


def render_python(table: dict[str, Any]) -> str:
    thresholds = "".join(
        f"    {json.dumps(k)}: {v!r},\n" for k, v in table["thresholds"].items()
    )
    langs = ", ".join(json.dumps(v) for v in table["languages"])
    return (
        f'"""{_BANNER}\n\n{_SOURCE}\n{_REGEN}\n\n'
        "Bundled as literals rather than read from disk so the published wheel is\n"
        'self-contained — conformance/ is not packaged.\n"""\n\n'
        "from __future__ import annotations\n\n"
        "__all__ = [\n"
        '    "CONFLICT_ANTONYMS",\n'
        '    "CONFLICT_LANGUAGES",\n'
        '    "CONFLICT_NEGATIONS",\n'
        '    "CONFLICT_REPORT_BIGRAMS",\n'
        '    "CONFLICT_SCOPE_MARKERS",\n'
        '    "CONFLICT_THRESHOLDS",\n'
        '    "MEASUREMENT_UNITS",\n'
        "]\n\n"
        f"CONFLICT_LANGUAGES: tuple[str, ...] = ({langs},)\n\n"
        + _py_strs("CONFLICT_NEGATIONS", table["negations"])
        + "\n"
        + _py_pairs("CONFLICT_ANTONYMS", table["antonyms"])
        + "\n"
        + _py_pairs("CONFLICT_REPORT_BIGRAMS", table["report_bigrams"])
        + "\n"
        + _py_strs("CONFLICT_SCOPE_MARKERS", table["scope_markers"])
        + "\n"
        + _py_strs("MEASUREMENT_UNITS", table["measurement_units"])
        + "\n"
        + "#: The pinned ADR-0007 thresholds, as data. The runtime constants live in\n"
        + "#: ``answer/conflict.py``; a test asserts the two agree, so a port cannot be\n"
        + "#: handed a number the reference does not actually use.\n"
        + f"CONFLICT_THRESHOLDS: dict[str, float | int] = {{\n{thresholds}}}\n"
    )


# --------------------------------------------------------------------------- #
# Go — embedded copy, mirroring golang/gate/stopwords.json.
# --------------------------------------------------------------------------- #

_GO = '''// {banner}
//
// {source}
// {regen}
//
// The JSON is EMBEDDED (a copy of conformance/conflict.json) so this module is
// self-contained as a Go dependency: a filesystem read of the shared
// conformance/ dir does not exist in the module cache. Same mechanism as
// golang/gate/stopwords.json and golang/answer/segmentation.json.

package answer

import (
\t_ "embed"
\t"encoding/json"
\t"sync"
)

//go:embed conflict_tables.json
var conflictTablesJSON []byte

// ConflictThresholds are the pinned ADR-0007 constants. They are data, on
// purpose: a port that quietly relaxes MaxResidual to 2 buys 4pp of recall and
// pays 15pp of false abstention, and pinning the number in the shared contract
// is the only way to catch that across languages.
type ConflictThresholds struct {{
\tSubjectOverlap          float64 `json:"subject_overlap"`
\tMaxSymdiff              int     `json:"max_symdiff"`
\tMaxResidual             int     `json:"max_residual"`
\tMinContent              int     `json:"min_content"`
\tDuplicateJaccard        float64 `json:"duplicate_jaccard"`
\tDuplicateMaxLengthDelta int     `json:"duplicate_max_length_delta"`
\tTopK                    int     `json:"top_k"`
}}

// ConflictTables is the canonical ADR-0007 table set.
type ConflictTables struct {{
\tLanguages        []string           `json:"languages"`
\tNegations        []string           `json:"negations"`
\tAntonyms         [][]string         `json:"antonyms"`
\tReportBigrams    [][]string         `json:"report_bigrams"`
\tScopeMarkers     []string           `json:"scope_markers"`
\tMeasurementUnits []string           `json:"measurement_units"`
\tThresholds       ConflictThresholds `json:"thresholds"`
}}

var (
\tconflictTablesOnce sync.Once
\tconflictTables     ConflictTables
)

// LoadConflictTables parses and caches the embedded canonical tables.
func LoadConflictTables() ConflictTables {{
\tconflictTablesOnce.Do(func() {{
\t\tif err := json.Unmarshal(conflictTablesJSON, &conflictTables); err != nil {{
\t\t\tpanic("answer: unmarshal conflict_tables.json: " + err.Error())
\t\t}}
\t}})
\treturn conflictTables
}}

// ConflictNegationSet returns the negation markers as a set.
func ConflictNegationSet() map[string]struct{{}} {{
\treturn stringSet(LoadConflictTables().Negations)
}}

// ConflictScopeMarkerSet returns the scope qualifiers as a set.
func ConflictScopeMarkerSet() map[string]struct{{}} {{
\treturn stringSet(LoadConflictTables().ScopeMarkers)
}}

// MeasurementUnitSet returns the unit tokens as a set.
func MeasurementUnitSet() map[string]struct{{}} {{
\treturn stringSet(LoadConflictTables().MeasurementUnits)
}}

// ConflictAntonymSet returns the antonym pairs SYMMETRISED — the canonical file
// stores each pair in one direction only.
func ConflictAntonymSet() map[[2]string]struct{{}} {{
\tout := map[[2]string]struct{{}}{{}}
\tfor _, pair := range LoadConflictTables().Antonyms {{
\t\tout[[2]string{{pair[0], pair[1]}}] = struct{{}}{{}}
\t\tout[[2]string{{pair[1], pair[0]}}] = struct{{}}{{}}
\t}}
\treturn out
}}

// ConflictReportBigramSet returns the reported-speech bigrams as a set. These
// are BIGRAMS deliberately: as unigrams they disable conflict detection across
// most legal text, where "claim" is a noun of art.
func ConflictReportBigramSet() map[[2]string]struct{{}} {{
\tout := map[[2]string]struct{{}}{{}}
\tfor _, pair := range LoadConflictTables().ReportBigrams {{
\t\tout[[2]string{{pair[0], pair[1]}}] = struct{{}}{{}}
\t}}
\treturn out
}}

func stringSet(values []string) map[string]struct{{}} {{
\tout := make(map[string]struct{{}}, len(values))
\tfor _, v := range values {{
\t\tout[v] = struct{{}}{{}}
\t}}
\treturn out
}}
'''


def render_go() -> str:
    return _GO.format(banner=_BANNER, source=_SOURCE, regen=_REGEN)


# --------------------------------------------------------------------------- #
# TypeScript — literals, mirroring js/src/gen/tables.ts.
# --------------------------------------------------------------------------- #


def render_ts(table: dict[str, Any]) -> str:
    lit = lambda value: json.dumps(value, indent=2)  # noqa: E731
    return f"""// {_BANNER}
// {_SOURCE}
// {_REGEN}
//
// Bundled rather than read from disk so the published package is self-contained
// (package.json `files` is ["dist"]; conformance/ is not published).

export const CONFLICT_LANGUAGES_TABLE: readonly string[] = {lit(table["languages"])};

export const CONFLICT_NEGATIONS_TABLE: readonly string[] = {lit(table["negations"])};

/** Stored in ONE direction; the reader symmetrises. */
export const CONFLICT_ANTONYMS_TABLE: readonly (readonly [string, string])[] = \
{lit(table["antonyms"])};

/** Reported speech, as BIGRAMS — as unigrams these disable detection in legal text. */
export const CONFLICT_REPORT_BIGRAMS_TABLE: readonly (readonly [string, string])[] = \
{lit(table["report_bigrams"])};

export const CONFLICT_SCOPE_MARKERS_TABLE: readonly string[] = {lit(table["scope_markers"])};

export const MEASUREMENT_UNITS_TABLE: readonly string[] = {lit(table["measurement_units"])};

/** The pinned ADR-0007 thresholds, as data — a port may not quietly relax one. */
export const CONFLICT_THRESHOLDS_TABLE: {{
  readonly subject_overlap: number;
  readonly max_symdiff: number;
  readonly max_residual: number;
  readonly min_content: number;
  readonly duplicate_jaccard: number;
  readonly duplicate_max_length_delta: number;
  readonly top_k: number;
}} = {lit(table["thresholds"])};
"""


def generate() -> dict[Path, str]:
    """All emitted artifacts as {absolute path: text}."""
    table = load()
    return {
        PY_OUT: render_python(table),
        GO_JSON_OUT: CANONICAL.read_text(encoding="utf-8"),
        GO_OUT: render_go(),
        TS_OUT: render_ts(table),
    }


def main() -> None:
    for path, text in generate().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(_REPO_ROOT)}")


if __name__ == "__main__":
    main()
