// GENERATED by python/scripts/gen_vision_prompt.py — DO NOT EDIT.
//
// Source of truth: <repo>/conformance/prompts.json (ADR-0005, ADR-0010 tier 2).
// Regenerate with: cd python && uv run python scripts/gen_vision_prompt.py
//
// The JSON is EMBEDDED (a copy of conformance/prompts.json) so this package is
// self-contained as a Go dependency: a filesystem read of the shared
// conformance/ dir does not exist in the module cache. Same mechanism as
// golang/answer/conflict_tables.json and golang/gate/stopwords.json.

package vision

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed prompts.json
var promptsJSON []byte

var (
	promptsOnce sync.Once
	prompts     map[string]string
)

// Prompts parses and caches the embedded canonical prompt table.
func Prompts() map[string]string {
	promptsOnce.Do(func() {
		if err := json.Unmarshal(promptsJSON, &prompts); err != nil {
			panic("vision: unmarshal prompts.json: " + err.Error())
		}
	})
	return prompts
}

// DescribePrompt is the pinned "vision_describe" prompt every emitted
// PendingRequest payload carries. It must be byte-identical across ports: the
// host POSTs the emitted payload VERBATIM, so a paraphrase here is a different
// model input and a different description in one language only.
func DescribePrompt() string {
	return Prompts()["vision_describe"]
}
